### PR TITLE
JWT flow for sailsforth http client

### PR DESCRIPTION
**Pull request by Elknar**

### CODE REVIEW

**Comment by simonlevesque** [comment]
looks good and simple. Do you think it could be possible to generalize this approach to be able to contribute this the main sails-forth project?

**Review by simonlevesque — APPROVED** [review]

**Comment by dball** [comment]
I'm flabbergasted that my idiosyncratic little library has literally any users outside our company. I'm glad you find some use in it!

I'm also curious if you could say anything about how to use configure and use JWT for authentication. The main authentication story in sails-forth is hilariously bad but is literally the only thing I could figure out how to work in the time period I had allotted to the task.

**Comment by Elknar** [comment]
@dball We actually had a similar issue... after some pointless back and forth with Salesforce support and deciphering [this thing](https://help.salesforce.com/articleView?id=remoteaccess_oauth_jwt_flow.htm&type=5), we figured out how to configure the connected app for it (more by pure chance than anything):

enable and add a certificate to the connected app: 
 - Under "API (Enable OAuth Settings)" click "Use digital signatures" and upload the cert. (Or, at least, I believe that's where it is supposed to go >_>)

After, you need to supply a JWT token as made by my `jwt-token` fn, with the same grant-type I wrote there.
 - `aud`/`host` needs to be one of "https://login.salesforce.com" or "https://test.saleforce.com"
 - `iss`/`client-id` is the consumer key for the connected app
 - `sub`/`username` - saleforce username
 - `exp` (generated by the fn, so no need to bother with it) - token expiration time. a small caveat: Salesforce docs say the token must expire within 5 minutes... but they don't seem to enforce it. If you need the token to last longer, you can do it, but 5 min (or maybe even shorter) us still probably the safer option - reduces the risk of a replay attack.

But, that's not all... One would expect this to work, especially if you configure the connected app to let users self-authorize... but nope. If you let users self-authorize (under "Manage connected apps"), you still need to have the user log in via browser at least once and have a refresh token issued (which can also expire at a later time, unless you set them to be persistent). Which is still not great, since using the API kinda implies you want to avoid the browser in the first place.

Luckily, there is an alternative: click edit in the "Manage connected app" thing and set the policy to "Permitted users: Admin-approved users are pre-authorized". Then, go back and click on the app name this time (very intuitive), and add a user under User Accounts. 

Afterwards, in theory, it should work... You create and sign a JWT token, send it with the above grant-type, and get an access token in return. Once the access token expires, just repeat the process for a new one. (Despite all the sadness before making it work, I prefer this method since it avoids having to record/pass around the password anywhere.)

Hope this helps?

**Comment by calvis** [comment]
Neat! The connected app portion of that setup sounds a lot like how we authenticate Salesforce DX in CircleCI, if it helps: https://trailhead.salesforce.com/en/modules/sfdx_travis_ci/units/sfdx_travis_ci_connected_app

**Comment by Elknar** [comment]
Interesting, haven't heard of Salesforce DX, but it does seem to be pretty much the same process

**Pull request merged**
